### ISSUE TITLE
New API v3

### ISSUE THREAD

**Issue by lucabartoli-ow** [HubSpot/hubspot-php#310]
Hi guys, new API v3 is out with a better organization and new useful endpoints.
We want to give our support to this awesome library.
It's probably better to bump the version of hubspot-php for the new implementation.
If you can give us all the contribution hints we need, we are glad to help.

**Comment by atanasiuk-hubspot** [comment]
API v3 SDK is placed in https://github.com/HubSpot/hubspot-api-php

**Comment by jamesgraham** [comment]
@atanasiuk-hubspot that SDK is great but it requires a total rewrite of the app and the docs are weak. For example, it is not clear how to get deals associated with a company e.g. : https://legacydocs.hubspot.com/docs/methods/crm-associations/crm-associations-overview

Being candid the migration docs are awful. Half the new API docs send you to legacy ones. Yet we are supposed to upgrade to the new library that doesn't support them? Think as a developer how that migration path is possible.

If we want to access a single API e.g. CRM Search can they be achieved via this SDK?

**Comment by lucabartoli** [comment]
> Half the new API docs send you to legacy ones. Yet we are supposed to upgrade to the new library that doesn't support them? Think as a developer how that migration path is possible.

Totally agree.
The new SDK is automatically generated and most of the time it's unnecessarily verbose (or doesn't always offer quick alternatives). It's a pity because the new API are instead well organized (not 100% complete, but well organized).

There is an open issue here https://github.com/HubSpot/hubspot-api-php/issues/11
I think it's critical to make the library more friendly, because otherwise we will need wrappers for the SDK itself.
